# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=4.1.6+26.1
maven_group=io.github.fishstiz
archives_base_name=cursors_extended
java_version=25
mod_id=cursors_extended
mod_name=Cursors Extended
mod_description=Configurable cursors for Minecraft.
mod_author=fishstiz
credits=demorogabrtz, Lucanoria, mpustovoi, ZeyMer1309, StarmanMine142
license=MIT
sources=https://github.com/fishstiz/cursors_extended
issues=https://github.com/fishstiz/cursors_extended/issues

# Common
minecraft_version=26.1-rc-2
loom_version=1.15-SNAPSHOT

# Fabric
# check these on https://fabricmc.net/develop
fabric_loader_version=0.18.4
fabric_api_version=0.143.15+26.1
minecraft_version_range_semver=>=26.1-alpha.5
modmenu_version=18.0.0-alpha.5

# Neoforge
mdg_version=2.0.140
neoforge_version=26.1.0.0-alpha.0+rc-1.20260319.164745
neoforge_version_range=[26.1.0.0-alpha.1,)
minecraft_version_range_maven=[26.1-rc-1,)
owo_version=U1h2fIEv