# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=4.0.0-beta.1+1.21.9
maven_group=io.github.fishstiz
archives_base_name=cursors_extended
java_version=21
mod_id=cursors_extended
mod_name=Cursors Extended
mod_description=Extended Minecraft Cursors.
mod_author=fishstiz
credits=demorogabrtz, Lucanoria, mpustovoi, ZeyMer1309, StarmanMine142
license=MIT
sources=https://github.com/fishstiz/cursors_extended
issues=https://github.com/fishstiz/cursors_extended/issues

# Common
minecraft_version=1.21.9-rc1
parchment_minecraft=1.21.8
parchment_version=2025.07.20

# Fabric
# check these on https://fabricmc.net/develop
fabric_loader_version=0.17.2
fabric_api_version=0.133.12+1.21.9
minecraft_version_range_semver=>=1.21.9-rc.1
modmenu_version=15.0.0-beta.1

# Neoforge
neoforge_loader_version_range=[4,)
neoforge_version=21.9.0-alpha.1.21.9-pre3.20250922.230103
neoforge_version_range=[21.9.0-alpha,)
minecraft_version_range_maven=[1.21.9-pre1,)