plugins {
    id 'multiloader-common'
    id 'fabric-loom'
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = 'Fabric'
                url = uri('https://maven.fabricmc.net')
            }
        }
        filter {
            includeGroup('net.fabricmc')
            includeGroup('fabric-loom')
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }

    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.7'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.0'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.0'
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

compileJava {
    enabled = false
}

remapJar {
    enabled = false
}

remapSourcesJar {
    enabled = false
}