import me.modmuss50.mpp.ReleaseType

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
}

neoForge {
    version = neoforge_version

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
            gameDirectory = project.file('run/client')
            setIdeName("NeoForge Client (${project.path})")
        }
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "Maven for PR #3002" // https://github.com/neoforged/NeoForge/pull/3002
        url = uri("https://prmaven.neoforged.net/NeoForge/pr3002")
        content {
            includeModule("net.neoforged", "neoforge")
            includeModule("net.neoforged", "testframework")
        }
    }
}

dependencies {
    implementation libs.fidgetz.neoforge
    jarJar libs.fidgetz.neoforge

    compileOnly "maven.modrinth:owo-lib:$owo_version"
}

processResources {
    // NeoForge doesn't have a way to enable a pack by default without making it required
    def defaultPack = "${sourceSets.main.output.resourcesDir}/resourcepacks/default"

    from("${defaultPack}/assets") {
        into "assets"
    }

    doLast {
        delete defaultPack
        delete "${sourceSets.main.output.resourcesDir}/${mod_id}.accesswidener"
        delete "${sourceSets.main.output.resourcesDir}/${mod_id}.classtweaker"
    }
}

publishMods {
    dryRun = Boolean.valueOf(dry_run)
    type = ReleaseType.of(release_type)
    changelog = rootProject.file("CHANGELOG.md").text
    file = jar.archiveFile
    additionalFiles.from(sourcesJar.archiveFile)
    displayName = "NeoForge v${this.version}"
    modLoaders.add("neoforge")

    github {
        parent rootProject.tasks.named("publishGithub")
        accessToken = findProperty("GITHUB_TOKEN") ?: ""
    }

    modrinth {
        accessToken = findProperty("MODRINTH_TOKEN") ?: ""
        minecraftVersions.addAll(modrinth_versions.split(','))
        projectId = modrinth_id
    }

    curseforge {
        accessToken = findProperty("CURSEFORGE_TOKEN") ?: ""
        projectId = curseforge_id
        minecraftVersions.addAll(curseforge_versions.split(','))
        client = true
    }
}

