plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
            gameDirectory = project.file('run/client')
            setIdeName("NeoForge Client (${project.path})")
        }
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    compileOnly "maven.modrinth:owo-lib:$owo_version"
}

processResources {
    // NeoForge doesn't have a way to enable a pack by default without making it required
    def defaultPack = "${sourceSets.main.output.resourcesDir}/resourcepacks/default"

    from("${defaultPack}/assets") {
        into "assets"
    }

    doLast {
        delete defaultPack
        delete "${sourceSets.main.output.resourcesDir}/${mod_id}.accesswidener"
    }
}
